services:
  rasa:
    build: .
    command: >
      rasa run
      --enable-api
      --cors "*"
      --debug
      --endpoints endpoints.yml
      --credentials credentials.yml
      --port 5005
    env_file:
      - .env
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    depends_on:
      - actions

  actions:
    build: .
    command: rasa run actions --actions actions --debug --port 5055
    env_file:
      - .env
    ports:
      - "5055:5055"
    volumes:
      - ./:/app
